### PR TITLE
unpatch poe api

### PR DESCRIPTION
**Pull request by xtekky**
added `poe-tag-id` security header

### CODE REVIEW

**Comment by CloudTronUSA** [comment]
This fixed the problem. Appreciate a lot!

**Comment by ading2210** [comment]
This looks good to me, but I just have one question. How did you find the `WpuLMiXEKKE98j56k` string? Was it just hardcoded in the client JS somewhere? If so, wouldn't it be really easy for Quora to break this library simply by changing that string again?

**Comment by xtekky** [comment]
it's hardcoded in the js, I would recommend using regex to find it. @ading2210 I can make another pull later

**Comment by krishna2206** [comment]
sorry I have a question , where in the JS did you get this string ?

**Comment by xtekky** [comment]
just search for it in the files, it should be in the file containing the md5 algorithm @krishna2206

**Comment by krishna2206** [comment]
> just search for it in the files, it should be in the file containing the md5 algorithm @krishna2206 

files ? can you point where are the files so I will search for it (sorry I'm a beginner when reverse engineering)

**Comment by Snowad14** [comment]
image

**Pull request merged**
