### PR TITLE
closes #128

### LINKED ISSUE #128: Stopped working
Seems like they updated their api and now it shows this error:
`Traceback (most recent call last):
  File "example.py", line 9, in <module>
    client = poe.Client(token)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 123, in __init__
    self.connect_ws()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 366, in connect_ws
    self.setup_connection()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 198, in get_next_data
    self.viewer = next_data["props"]["pageProps"]["payload"]["viewer"]`

### PR DESCRIPTION
**Pull request by alqasemy2020**
`payload` had to be replaced with `data` keyword in lines 198, 209, 262 and 267

### CODE REVIEW

**Comment by canxin121** [comment]
Not all situations and places should be replaced by payload with data, your changes will cause more errors.

**Comment by alqasemy2020** [comment]
nope. I didn't replace them all. only those which where affected by the new changes made by poe.com. 

you won't be able to run either the get_bot or explore_bots functions unless you replace that keyword in both functions, which you didn't do in your PR

**Comment by canxin121** [comment]
Yes,explore_bots and get_bot should be changed ,too.But another issue is payload and data both appears sometimes,using if else maybe better

**Comment by ading2210** [comment]
This PR has been superseded by #131 and #132.

**Pull request closed without merging**
