### PR TITLE
Code re-format + thread for recv_post

### PR DESCRIPTION
**Pull request by GenifeUA**
This will improve the code a bit visually + probably add a temporary solution to remove the wait after the end of the response (moved to the thread)

### CODE REVIEW

**Comment by ading2210** [comment]
Please do not change the indentation of the entire project.

**Comment by GenifeUA** [comment]
AHAHAH, ok 🙂

**Comment by GenifeUA** [comment]
> Funniest PR ever ngl

Why funny?

**Comment by GenifeUA** [comment]
Explain more, please. This is one of my first pull requests

**Comment by kxtzownsu** [comment]
Me when I change the entire indentation and make 3 lines of code into 7

**Pull request closed without merging**
